#PBS -l walltime=24:00:00
#PBS -l ncpus=12
#PBS -l mem=14G
#PBS -N align

module load bwakit
cd /mnt/backedup/home/conradL/git/streammd/scratch

seqtk mergepe /mnt/lustre/working/genomeinfo/data/20160328_Melanoma/MELA_0102/seq_final/Melanoma_MELA0102_1DNA_5ControlCellLineDerivedFromNormalTissue_EXTERNMELA20140924104_Unknown0_NoCapture_Bwa_HiSeq/140924_EXTERN_0588_AC1DTBACXX.lane_2.nobc.1.fastq.gz /mnt/lustre/working/genomeinfo/data/20160328_Melanoma/MELA_0102/seq_final/Melanoma_MELA0102_1DNA_5ControlCellLineDerivedFromNormalTissue_EXTERNMELA20140924104_Unknown0_NoCapture_Bwa_HiSeq/140924_EXTERN_0588_AC1DTBACXX.lane_2.nobc.2.fastq.gz |cutadapt --trim-n --interleaved -a file:/reference/genomeinfo/adapters/IlluminaGenericAdapters_R1.fa -A file:/reference/genomeinfo/adapters/IlluminaGenericAdapters_R2.fa -|bwa mem -t 6 -p -K 100000000 /reference/genomes/GRCh37_ICGC_standard_v2/indexes/BWAKIT_0.7.12/GRCh37_ICGC_standard_v2.fa - 2>/dev/null |samtools sort -@ 6 -m 6G -|samtools view -b - > 140924_EXTERN_0588_AC1DTBACXX.lane_2.nobc.coordsort.bam

